name: OpenSSF Scorecard

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 5' # every Friday at 12:00 UTC

permissions:
  id-token: write
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif

      - name: Upload to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
